services:
  db:
    image: dhi.io/postgres:18.3-debian13
    container_name: krankenhaus-ki-postgres
    ports:
      - published: 5432
        target: 5432
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: p
    volumes:
      - pg_data_krankenhaus_ki:/var/lib/postgresql/18/data
    healthcheck:
      test: ["CMD", "pg_isready", "--dbname=postgres", "--username=postgres"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s

volumes:
  pg_data_krankenhaus_ki:
