services:
  db:
    image: dhi.io/postgres:18.3-debian13
    ports:
      - published: 5432
        target: 5432
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: p
    volumes:
      - pg_data_krankenhaus_ki:/var/lib/postgresql/18/data
    healthcheck:
      test: ["CMD", "pg_isready", "--dbname=postgres", "--username=postgres"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev
    ports:
      - published: 8880
        target: 8080
    environment:
      TZ: Europe/Berlin
      KC_BOOTSTRAP_ADMIN_USERNAME: tmp
      KC_BOOTSTRAP_ADMIN_PASSWORD: p
    volumes:
      - keycloak_data_krankenhaus_ki:/opt/keycloak/data

volumes:
  pg_data_krankenhaus_ki:
  keycloak_data_krankenhaus_ki:
